[tool.poetry]
name = "sample"
version = "0.1.0"
description = ""
authors = ["Shankar <shankardhandapani1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pygame = "^1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
